### ISSUE TITLE
unknown pongo2.Error field 'ErrorMsg' in struct literal

### ISSUE THREAD

**Issue by siredwin** [flosch/pongo2-addons#4]
I am all of a sudden starting to get this error. What could be causing this? Below is the offending output.

.openshift/g/src/github.com/flosch/pongo2-addons/filters.go:225: unknown pongo2.Error field 'ErrorMsg' in struct literal
.openshift/g/src/github.com/flosch/pongo2-addons/filters.go:234: unknown pongo2.Error field 'ErrorMsg' in struct literal
.openshift/g/src/github.com/flosch/pongo2-addons/filters.go:257: unknown pongo2.Error field 'ErrorMsg' in struct literal
.openshift/g/src/github.com/flosch/pongo2-addons/filters.go:267: unknown pongo2.Error field 'ErrorMsg' in struct literal

**Comment by siredwin** [comment]
Never mind. I see it is a pongo2 branch issue. Pulling some versions will create that problem

**Comment by flosch** [comment]
Will be fixed very soon in https://github.com/flosch/pongo2-addons/pull/3

**Comment by flosch** [comment]
Fixed in tip.
